@InventoryMaster_HostAddress = http://localhost:5155
@InventoryMaster_Username = admin
@InventoryMaster_Password = admin
@InventoryMaster_Auth = Basic
@InventoryMaster_AuthHeader = Basic
@InventoryMaster_AuthHeaderValue = Basic
